#:kivy 1.9.1

<EC>:
    Label:
        font_size: 50
        text_size: self.size
        halign: 'right'
        center_x: root.width / 2
        top: root.top - 50
        text: "To receive £"
            
    Label:
        font_size: 50
        center_x: root.width / 4
        top: root.top - 100
        text: "When fee is"
            
    Label:
        font_size: 50
        center_x: root.width / 4
        top: root.top - 150
        text: "Send £"